# Test epidemiology simulator

In [1]:
import numpy as np
from goldmine.simulators.epidemiology import Epidemiology

In [2]:
simulator = Epidemiology()

## Run simulation

In [3]:
theta = np.array([3.59,0.59,0.097])

In [4]:
x = simulator.rvs(theta, 1)


[[0.0708  0.0649  0.059   ... 0.00295 0.00295 0.00295]
 [0.0708  0.0649  0.059   ... 0.00295 0.00295 0.00295]
 [0.0708  0.0649  0.059   ... 0.00295 0.00295 0.00295]
 ...
 [0.0708  0.0649  0.059   ... 0.00295 0.00295 0.00295]
 [0.0708  0.0649  0.059   ... 0.00295 0.00295 0.00295]
 [0.0708  0.0649  0.059   ... 0.00295 0.00295 0.00295]]
25
0.0059
-116.0909853259271

[[0.24339615 0.16845769 0.19707692 ... 0.00295    0.00295    0.00295   ]
 [0.24339615 0.16845769 0.19707692 ... 0.00295    0.00295    0.00295   ]
 [0.02360943 0.0163404  0.01911646 ... 0.00028615 0.00028615 0.00028615]
 ...
 [0.24339615 0.16845769 0.19707692 ... 0.00295    0.00295    0.00295   ]
 [0.24339615 0.16845769 0.19707692 ... 0.00295    0.00295    0.00295   ]
 [0.24339615 0.16845769 0.19707692 ... 0.00295    0.00295    0.00295   ]]
72
0.00295
-345.4687482833274

[[0.00000000e+00 2.75016141e-02 2.63712532e-02 ... 2.86150000e-04
  2.86150000e-04 1.62549615e-03]
 [0.00000000e+00 2.75016141e-02 2.63712532e-02 ... 2.861500

/Users/johannbrehmer/work/projects/higgs_inference/goldmine/goldmine/simulators/epidemiology.py:113: RuntimeWarning: divide by zero encountered in true_divide
  * np.broadcast_to(1. / np.sum(state, axis=1), (self.n_strains,  self.n_individuals)).T)
/Users/johannbrehmer/work/projects/higgs_inference/goldmine/goldmine/simulators/epidemiology.py:113: RuntimeWarning: invalid value encountered in multiply
  * np.broadcast_to(1. / np.sum(state, axis=1), (self.n_strains,  self.n_individuals)).T)


In [6]:
x

array([[ 2.7735266 , 21.        ,  0.54716981,  0.33962264]])