# Random walk

In [1]:
import sys
import numpy as np
import corner
from matplotlib import pyplot as plt
%matplotlib inline
import logging

from goldmine.simulators.random_walk_checkpointed import CheckpointedRandomWalk

In [2]:
logging.basicConfig(format='%(asctime)s  %(message)s', datefmt='%H:%M')
logging.getLogger().setLevel(logging.DEBUG)

## Simulate random walk

In [3]:
sim = CheckpointedRandomWalk()

In [4]:
x0, t_xz0, z_checkpoints0, t_xz_checkpoints0 = sim.rvs_score([100.], [100.], 1)

17:17  Simulating 1 evolutions for theta = [100.0], augmenting with joint score
17:17    Starting sample 1 of 1
/Users/johannbrehmer/anaconda3/envs/higgs_inference/lib/python3.6/site-packages/autograd/tracer.py:14: UserWarning: Output seems independent of input.
  warnings.warn("Output seems independent of input.")
17:17  Step up at t = 0.0020072626629180617
17:17  Step down at t = 0.006064878768922428
17:17  Step up at t = 0.0063619996369413435
17:17  Step up at t = 0.010149000069823926
17:17  Step up at t = 0.0015861820176005757
17:17  Step down at t = 0.003341140682808986
17:17  Step up at t = 0.0015542156517802672
17:17  Step down at t = 0.0015705175083952855
17:17  Step down at t = 0.004965622578568425
17:17  Step up at t = 0.00028537463971814876
17:17  Step up at t = 0.0022335464694650167
17:17  Step down at t = 0.0007986789441641047
17:17  Step down at t = 0.0014487688762729464
17:17  Step down at t = 0.0004926245222694149
17:17  Step down at t = 0.001390378751399109
17:17  Step

17:17  Step up at t = 0.00014860620410408841
17:17  Step down at t = 0.004584245317259566
17:17  Step up at t = 0.0005190219654627824
17:17  Step up at t = 0.006723415630801142
17:17  Step up at t = 0.0016862780502228804
17:17  Step up at t = 0.012421990021549138
17:17  Step up at t = 7.883696675768678e-05
17:17  Step up at t = 0.006520979453374491
17:17  Step up at t = 0.006380084221504785
17:17  Step down at t = 0.003261505612629249
17:17  Step down at t = 0.010414228476060319
17:17  Step up at t = 0.0043104775430357865
17:17  Step down at t = 6.359438500706146e-05
17:17  Step up at t = 0.003770965873090696
17:17  Step up at t = 0.014174366934636152
17:17  Step up at t = 0.006394692043878258
17:17  Step up at t = 0.0031347746609448317
17:17  Step down at t = 0.003721706113045349
17:17  Step down at t = 0.02936127846578274
17:17  Step down at t = 0.001789626384235261
17:17  Step down at t = 0.002980482382848376
17:17  Step up at t = 0.004601318346854032
17:17  Step up at t = 0.0097199

In [5]:
x1, t_xz1, z_checkpoints1, t_xz_checkpoints1 = sim.rvs_score([200.], [100.], 1)

17:17  Simulating 1 evolutions for theta = [200.0], augmenting with joint score
17:17    Starting sample 1 of 1
17:17  Step down at t = 0.00854066090525795
17:17  Step up at t = 0.004471811603557175
17:17  Step down at t = 0.001455499921941729
17:17  Step up at t = 0.011553433900748119
17:17  Step up at t = 0.0020951209458670178
17:17  Step up at t = 0.0047037930369006236
17:17  Step down at t = 0.0017803656318717588
17:17  Step up at t = 0.0001540356543079028
17:17  Step up at t = 0.009033239579615998
17:17  Step down at t = 0.002438484074907104
17:17  Step up at t = 0.0009976771725217458
17:17  Step up at t = 0.005471941029922753
17:17  Step up at t = 0.0036415072582450924
17:17  Step up at t = 0.029169202984588978
17:17  Step down at t = 0.001281763284440605
17:17  Step up at t = 0.0016773628442663263
17:17  Step up at t = 0.00042295329136531274
17:17  Step down at t = 0.004989527532929982
17:17  Step up at t = 0.002827784702039311
17:17  Step down at t = 0.029891204319044566
17:17 

17:17  Step up at t = 0.001619115787642833
17:17  Step down at t = 0.00037860591091782214
17:17  Step up at t = 0.00015295267493522325
17:17  Step up at t = 0.0005265908033035332
17:17  Step up at t = 0.003808861885555794
17:17  Step up at t = 0.003100709023153933
17:17  Step down at t = 0.001407691459475534
17:17  Step up at t = 0.001875905683223697
17:17  Step up at t = 0.001731788800264696
17:17  Step up at t = 0.00548660704523429
17:17  Step up at t = 0.0024149975168169372
17:17  Step up at t = 0.003754398965444318
17:17  Step up at t = 9.857917558630536e-05
17:17  Step up at t = 0.0015169537201102027
17:17  Step up at t = 0.00045106379195369677
17:17  Step down at t = 0.005335330521950877
17:17  Step up at t = 0.008299186077652322
17:17  Step down at t = 0.0026794792783162266
17:17  Step down at t = 0.0031152052930590816
17:17  Step down at t = 0.009820783037539723
17:17  Step up at t = 0.0020094208642898485
17:17  Step up at t = 0.0013968074240109907
17:17  Step up at t = 0.00563

In [6]:
z_checkpoints1

array([[0, 6, 17, 28, 38, 57, 71, 89, 104, 112, 122]], dtype=object)

In [7]:
t_xz_checkpoints1

array([[[0.        ],
        [0.00340263],
        [0.08361641],
        [0.13180801],
        [0.1030648 ],
        [0.14698901],
        [0.09057648],
        [0.20012901],
        [0.12538204],
        [0.06305041],
        [0.06080339]]])

In [8]:
t_xz1

array([[1.0088222]])